import type { Language } from './index';

export const extraTranslations: Record<Language, Record<string, string>> = {
  fr: {
    solarDescription:'La puissance PV nécessaire est calculée à partir de votre consommation quotidienne.', peakSunHint:"Estimation de l'énergie solaire quotidienne disponible, en heures équivalentes de plein soleil.", efficiencyHint:'Pertes combinées (câblage, onduleur, température…), entre 0 et 1.', theoreticalPv:'Puissance PV théorique nécessaire', searchPanel:'Rechercher une marque ou un modèle de panneau…', editableFields:'Les champs ci-dessous restent modifiables manuellement, y compris après une sélection dans le catalogue.', panelFeatures:'Caractéristiques du panneau', panelCount:'Nombre de panneaux', installedPower:'Puissance installée', gapNeed:'Écart / besoin', inverterLimits:"Limites de l'onduleur / contrôleur", compatible:'Configuration compatible', continueBattery:'Continuer vers la batterie', batteryDescription:'Tension système : {voltage} V.', autonomy:'Autonomie souhaitée (jours)', chosenBattery:'Batterie choisie', continueInverter:"Continuer vers l’onduleur", inverterDescription:"Calculé à partir des puissances nominale et de démarrage de tous les appareils saisis à l'étape 2.", startupUnknown:'Non renseignée', continueController:'Continuer vers le contrôleur', hybridNote:'Système hybride : le champ PV et la batterie sont gérés par un seul convertisseur hybride intégré.', controllerDescription:"Choisissez d'abord le type de contrôleur, puis un modèle dans le catalogue.", currentMargin:'Courant recommandé (marge incluse)', continueCabling:'Continuer vers le câblage', cablingDescription:'Section de câble entre le champ PV et le contrôleur, et calibre de la protection DC côté champ.', fieldNotSized:"Le champ photovoltaïque n'est pas encore dimensionné.", fieldCurrent:'Courant du champ (Isc)', recommendedProtection:'Calibre protection recommandé', voltageDrop:'Chute de tension', protection:'Protection DC', seeResults:'Voir les résultats', insufficientData:'Données insuffisantes', warning:'Avertissements et recommandations', disclaimer:'Ce rapport constitue une estimation de dimensionnement. Une validation par un professionnel qualifié est recommandée avant toute installation.'
  },
  en: {
    solarDescription:'Required PV power is calculated from your daily consumption.', peakSunHint:'Estimated daily solar energy available, in equivalent full-sun hours.', efficiencyHint:'Combined losses (wiring, inverter, temperature…), between 0 and 1.', theoreticalPv:'Required theoretical PV power', searchPanel:'Search for a panel brand or model…', editableFields:'The fields below remain editable, including after selecting from the catalog.', panelFeatures:'Panel characteristics', panelCount:'Number of panels', installedPower:'Installed power', gapNeed:'Gap / need', inverterLimits:'Inverter / controller limits', compatible:'Compatible configuration', continueBattery:'Continue to battery', batteryDescription:'System voltage: {voltage} V.', autonomy:'Desired autonomy (days)', chosenBattery:'Selected battery', continueInverter:'Continue to inverter', inverterDescription:'Calculated from nominal and startup power of all devices entered in step 2.', startupUnknown:'Not provided', continueController:'Continue to controller', hybridNote:'Hybrid system: PV and battery are managed by one integrated hybrid converter.', controllerDescription:'First choose a controller type, then a model from the catalog.', currentMargin:'Recommended current (margin included)', continueCabling:'Continue to wiring', cablingDescription:'Cable section between the PV array and controller, plus DC protection rating.', fieldNotSized:'The PV array has not been sized yet.', fieldCurrent:'Array current (Isc)', recommendedProtection:'Recommended protection rating', voltageDrop:'Voltage drop', protection:'DC protection', seeResults:'View results', insufficientData:'Insufficient data', warning:'Warnings and recommendations', disclaimer:'This report is a sizing estimate. Validation by a qualified professional is recommended before installation.'
  },
  es: {
    solarDescription:'La potencia FV necesaria se calcula a partir del consumo diario.', peakSunHint:'Estimación de la energía solar diaria disponible, en horas equivalentes de sol pleno.', efficiencyHint:'Pérdidas combinadas (cableado, inversor, temperatura…), entre 0 y 1.', theoreticalPv:'Potencia FV teórica necesaria', searchPanel:'Buscar una marca o modelo de panel…', editableFields:'Los campos siguientes siguen siendo editables después de seleccionar del catálogo.', panelFeatures:'Características del panel', panelCount:'Número de paneles', installedPower:'Potencia instalada', gapNeed:'Diferencia / necesidad', inverterLimits:'Límites del inversor / controlador', compatible:'Configuración compatible', continueBattery:'Continuar a la batería', batteryDescription:'Tensión del sistema: {voltage} V.', autonomy:'Autonomía deseada (días)', chosenBattery:'Batería elegida', continueInverter:'Continuar al inversor', inverterDescription:'Calculado a partir de las potencias nominal y de arranque de los equipos de la etapa 2.', startupUnknown:'No indicada', continueController:'Continuar al controlador', hybridNote:'Sistema híbrido: el campo FV y la batería son gestionados por un convertidor híbrido integrado.', controllerDescription:'Elija primero el tipo de controlador y después un modelo del catálogo.', currentMargin:'Corriente recomendada (margen incluido)', continueCabling:'Continuar al cableado', cablingDescription:'Sección del cable entre el campo FV y el controlador, y calibre de protección CC.', fieldNotSized:'El campo FV aún no está dimensionado.', fieldCurrent:'Corriente del campo (Isc)', recommendedProtection:'Calibre de protección recomendado', voltageDrop:'Caída de tensión', protection:'Protección CC', seeResults:'Ver resultados', insufficientData:'Datos insuficientes', warning:'Advertencias y recomendaciones', disclaimer:'Este informe es una estimación de dimensionamiento. Se recomienda validación profesional antes de instalar.'
  },
  ar: {
    solarDescription:'يتم حساب قدرة PV المطلوبة انطلاقاً من استهلاكك اليومي.', peakSunHint:'تقدير الطاقة الشمسية اليومية المتاحة بساعات الشمس الكاملة.', efficiencyHint:'الخسائر المجمعة (الأسلاك والعاكس ودرجة الحرارة)، بين 0 و1.', theoreticalPv:'قدرة PV النظرية المطلوبة', searchPanel:'ابحث عن علامة أو طراز اللوح…', editableFields:'يمكن تعديل الحقول أدناه حتى بعد الاختيار من الكتالوج.', panelFeatures:'خصائص اللوح', panelCount:'عدد الألواح', installedPower:'القدرة المركبة', gapNeed:'الفارق / الحاجة', inverterLimits:'حدود العاكس / وحدة التحكم', compatible:'إعداد متوافق', continueBattery:'المتابعة إلى البطارية', batteryDescription:'جهد النظام: {voltage} فولت.', autonomy:'الاستقلالية المطلوبة (أيام)', chosenBattery:'البطارية المختارة', continueInverter:'المتابعة إلى العاكس', inverterDescription:'يُحسب من القدرة الاسمية وقدرة بدء تشغيل جميع الأجهزة في الخطوة 2.', startupUnknown:'غير مُدخل', continueController:'المتابعة إلى وحدة التحكم', hybridNote:'نظام هجين: تتم إدارة PV والبطارية بواسطة محول هجين مدمج.', controllerDescription:'اختر نوع وحدة التحكم أولاً ثم نموذجاً من الكتالوج.', currentMargin:'التيار الموصى به (مع الهامش)', continueCabling:'المتابعة إلى الأسلاك', cablingDescription:'مقطع الكابل بين مصفوفة PV ووحدة التحكم وتصنيف حماية DC.', fieldNotSized:'لم يتم تصميم مصفوفة PV بعد.', fieldCurrent:'تيار المصفوفة (Isc)', recommendedProtection:'تصنيف الحماية الموصى به', voltageDrop:'هبوط الجهد', protection:'حماية DC', seeResults:'عرض النتائج', insufficientData:'بيانات غير كافية', warning:'تحذيرات وتوصيات', disclaimer:'هذا التقرير تقدير للتصميم. يوصى بالتحقق من طرف مختص قبل التركيب.'
  },
  sw: {
    solarDescription:'Nguvu ya PV inayohitajika hukokotolewa kutokana na matumizi ya kila siku.', peakSunHint:'Makadirio ya nishati ya jua inayopatikana kwa siku.', efficiencyHint:'Hasara za pamoja (wiring, inverter, joto), kati ya 0 na 1.', theoreticalPv:'Nguvu ya PV inayohitajika', searchPanel:'Tafuta chapa au modeli ya paneli…', editableFields:'Sehemu zilizo hapa chini zinaweza kubadilishwa hata baada ya kuchagua katalogi.', panelFeatures:'Sifa za paneli', panelCount:'Idadi ya paneli', installedPower:'Nguvu iliyowekwa', gapNeed:'Tofauti / hitaji', inverterLimits:'Mipaka ya inverter / kidhibiti', compatible:'Muundo unaolingana', continueBattery:'Endelea kwenye betri', batteryDescription:'Voltage ya mfumo: {voltage} V.', autonomy:'Uhuru unaotakiwa (siku)', chosenBattery:'Betri iliyochaguliwa', continueInverter:'Endelea kwenye inverter', inverterDescription:'Hukokotolewa kutokana na nguvu ya kawaida na ya kuanza ya vifaa katika hatua ya 2.', startupUnknown:'Haijawekwa', continueController:'Endelea kwenye kidhibiti', hybridNote:'Mfumo wa mseto: PV na betri zinasimamiwa na kibadilishaji mseto kilichounganishwa.', controllerDescription:'Chagua aina ya kidhibiti kwanza, kisha modeli kutoka katalogi.', currentMargin:'Mkondo unaopendekezwa (pamoja na marge)', continueCabling:'Endelea kwenye wiring', cablingDescription:'Sehemu ya kebo kati ya PV na kidhibiti pamoja na ulinzi wa DC.', fieldNotSized:'Mfumo wa PV bado haujakadiriwa.', fieldCurrent:'Mkondo wa mfumo (Isc)', recommendedProtection:'Kiwango cha ulinzi kinachopendekezwa', voltageDrop:'Mteremko wa voltage', protection:'Ulinzi wa DC', seeResults:'Tazama matokeo', insufficientData:'Data haitoshi', warning:'Maonyo na mapendekezo', disclaimer:'Ripoti hii ni makadirio ya ukubwa. Uthibitisho wa mtaalamu unapendekezwa kabla ya ufungaji.'
  }
};

Object.assign(extraTranslations.fr, {
  heroDescription:'Dimensionnez votre installation à partir de votre consommation électrique : champ PV, batterie, onduleur et contrôleur, calculés automatiquement à chaque modification, à partir de catalogues d’équipements réels.',
  disclaimer:'Les résultats fournis sont des estimations de dimensionnement et doivent être vérifiés par un professionnel qualifié avant toute installation.',
});
Object.assign(extraTranslations.en, {
  heroDescription:'Size your installation from your electricity consumption: PV array, battery, inverter and controller calculated automatically from real equipment catalogs.',
  disclaimer:'The results provided are sizing estimates and must be checked by a qualified professional before installation.',
});
Object.assign(extraTranslations.es, {
  heroDescription:'Dimensione su instalación a partir de su consumo eléctrico: campo FV, batería, inversor y controlador calculados automáticamente con catálogos reales.',
  disclaimer:'Los resultados son estimaciones y deben ser verificados por un profesional cualificado antes de cualquier instalación.',
});
Object.assign(extraTranslations.ar, {
  heroDescription:'صمّم نظامك انطلاقاً من استهلاكك الكهربائي: يتم حساب مصفوفة PV والبطارية والعاكس ووحدة التحكم تلقائياً من كتالوجات حقيقية.',
  disclaimer:'النتائج المقدمة تقديرات تصميم ويجب التحقق منها بواسطة مختص مؤهل قبل التركيب.',
});
Object.assign(extraTranslations.sw, {
  heroDescription:'Kadiria mfumo wako kutokana na matumizi ya umeme: PV, betri, inverter na kidhibiti hukokotolewa moja kwa moja kutoka katalogi halisi.',
  disclaimer:'Matokeo haya ni makadirio ya ukubwa na lazima yakaguliwe na mtaalamu aliyehitimu kabla ya ufungaji.',
});
Object.assign(extraTranslations.fr, { aboutText2:"L'application calcule le bilan énergétique, la puissance PV, les panneaux, la batterie, l'onduleur, le contrôleur et le câblage à partir de formules techniques usuelles et de catalogues réels.", aboutText3:'Les résultats sont des estimations et doivent être validés par un professionnel qualifié avant toute installation.' });
Object.assign(extraTranslations.en, { aboutText2:'The application calculates the energy balance, PV power, panels, battery, inverter, controller and wiring using common technical formulas and real equipment catalogs.', aboutText3:'The results are estimates and must be validated by a qualified professional before installation.' });
Object.assign(extraTranslations.es, { aboutText2:'La aplicación calcula el balance energético, la potencia FV, los paneles, la batería, el inversor, el controlador y el cableado mediante fórmulas técnicas y catálogos reales.', aboutText3:'Los resultados son estimaciones y deben ser validados por un profesional cualificado antes de instalar.' });
Object.assign(extraTranslations.ar, { aboutText2:'يحسب التطبيق ميزان الطاقة وقدرة PV والألواح والبطارية والعاكس ووحدة التحكم والأسلاك باستخدام المعادلات التقنية والكتالوجات الحقيقية.', aboutText3:'النتائج تقديرات ويجب اعتمادها من مختص مؤهل قبل التركيب.' });
Object.assign(extraTranslations.sw, { aboutText2:'Programu hukokotoa mizani ya nishati, nguvu ya PV, paneli, betri, inverter, kidhibiti na wiring kwa kutumia kanuni za kiufundi na katalogi halisi.', aboutText3:'Matokeo ni makadirio na lazima yathibitishwe na mtaalamu aliyehitimu kabla ya ufungaji.' });
